UserStories
WordsMemorizer/Documentation pull request #2
Opened 2021-07-10 13:25 UTC by LastSprint

Оформил US

2021-07-11 13:06 UTC, drxlx commented
<img width="1327" alt="image" src="https://user-images.githubusercontent.com/15323858/125196242-c9c88980-e261-11eb-97cf-fa746b2205b0.png">
чет с форматом дока странное, что его ричдиф не берет

мб добавить uml диаграмму, майнд карту или какое-либо визуальное описание?

2021-07-11 13:07 UTC, drxlx requested changes
см коммент выше

2021-08-01 15:09 UTC, LastSprint commented
В следующем PR-е

2021-08-01 15:09 UTC, LastSprint commented
Там вроде все норм с форматом, если открыть просто просмотрщиком. Да и дифф у меня показывается

2021-08-01 15:10 UTC, merged